version: '3.6'
services:
  storeDb:
    container_name: storeDb
    image: api-store-bd:1.0
    volumes:
      - /volume/shCript:/shScript
    environment:
      Lang: en_us.utf-8
      seconds: 240
    command: sh -c " java -jar -Dfile.encoding=UTF8 jar/filldataBase.jar $${seconds}"
    